apiVersion: v1
kind: Service
metadata:
  name: my-project-service
spec:
  selector:
    app: my-project
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 80         # Service port inside cluster
      targetPort: 3000 # Port your container listens on
      nodePort: 30080  # Port exposed on each node (choose 30000â€“32767)

