apiVersion: v1
kind: Service
metadata:
  name: my-project-service
  namespace: project
spec:
  selector:
    app: my-project
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
