name: GitOps Deploy My Project

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Docker login
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build & push image
      run: |
        docker build -t haydar26/my-project:${{ github.sha }} .
        docker push haydar26/my-project:${{ github.sha }}

    - name: Update image tag
      run: |
        sed -i 's|image: .*|image: haydar26/my-project:${{ github.sha }}|' base/deployment.yaml

    - name: Commit and push
      run: |
        git config user.name "gitops-bot"
        git config user.email "gitops@github"
        git commit -am "Update image to ${{ github.sha }}"
        git push
