apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: web-routes
  namespace: exercises
spec:
  parentRefs:
  - name: web-gateway

  rules:
  # log-output at /
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: log-output-service
      port: 80

  # ping-pong at /pingpong â†’ rewritten to /
  - matches:
    - path:
        type: PathPrefix
        value: /pingpong
    filters:
    - type: URLRewrite
      urlRewrite:
        path:
          type: ReplacePrefixMatch
          replacePrefixMatch: /
    backendRefs:
    - name: ping-pong
      port: 3000
