apiVersion: v1
kind: Service
metadata:
  name: greeter-svc
spec:
  selector:
    app: greeter
  ports:
    - port: 80
      targetPort: 5678
---
apiVersion: v1
kind: Service
metadata:
  name: greeter-svc-v1
spec:
  selector:
    app: greeter
    version: v1
  ports:
    - port: 80
      targetPort: 5678
---
apiVersion: v1
kind: Service
metadata:
  name: greeter-svc-v2
spec:
  selector:
    app: greeter
    version: v2
  ports:
    - port: 80
      targetPort: 5678
