apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: log-output-ingress
spec:
  rules:
  - http: # <--- The hyphen indicates the start of a list item
      paths:
      - path: /status
        pathType: Prefix
        backend:
          service:
            name: log-output-service
            port:
              number: 80