apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml

  - configmap-log-output.yaml
  - log-output-deployment.yaml
  - log-output-service.yaml

  - pingpong-deployment.yaml
  - pingpong-service.yaml

  - greeter-v1.yaml
  - greeter-v2.yaml
  - greeter-services.yaml
  - greeter-httproute.yaml

  - gateway.yaml
