apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - log-output/configmap.yaml
  - log-output/deployment.yaml
  - log-output/service.yaml
  - ping-pong/deployment.yaml
  - ping-pong/service.yaml
  - gateway.yaml
  - httproute.yaml
