apiVersion: v1
kind: Service
metadata:
  name: ping-pong-service
spec:
  selector:
    app: ping-pong
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000 # The container listens on 3000