apiVersion: v1
kind: Service
metadata:
  name: todo-service
spec:
  selector:
    app: todo
  type: NodePort
  ports:
    - protocol: TCP
      port: 80         # ClusterIP port
      targetPort: 3000 # container port
      nodePort: 30080  # external NodePort
