apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-project
  template:
    metadata:
      labels:
        app: my-project
    spec:
      containers:
      - name: my-project
        image: haydar26/my-project:REPLACE_WITH_SHA
        ports:
        - containerPort: 3000
        env:
        - name: EXAMPLE_ENV
          value: "HelloWorld"
        - name: FORWARD_EXTERNAL
          value: "true"
        - name: DB_BACKUP_ENABLED
          value: "true"
